apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: pingpong
          image: pingpong:latest
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
          imagePullPolicy: Never 
          ports:
            - containerPort: 8080