apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: config-volume
          configMap:
            name: log-output-config
      containers:
        - name: log-writer
          image: jannekarki/log-writer:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
        - name: log-reader
          image: jannekarki/log-reader:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
            - name: config-volume
              mountPath: /usr/src/app/config/information.txt
              subPath: information.txt
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
