apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: log-writer
          image: log-writer:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
        - name: log-reader
          image: log-reader:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
