apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: project-namespace
data:
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "tododb"
  BACKEND_SERVICE_URL: "http://todo-backend-svc:8080"
