apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-app-volume
          persistentVolumeClaim:
            claimName: todo-app-pvc
      containers:
      - name: todo-app
        image: jannekarki/todo-app:1.4
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
        volumeMounts:
          - name: todo-app-volume
            mountPath: /usr/src/app/files
        env:
          - name: BACKEND_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: BACKEND_SERVICE_URL