FROM python:3.9-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY log-reader.py .

RUN mkdir -p /usr/src/app/config

RUN pip install flask requests

CMD ["python", "log-reader.py"]

