name: Deploy to GKE

on:
  push:


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE: todo-app
  BACKEND_IMAGE: todo-backend
  BRANCH: ${{ github.ref_name }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build-publish-deploy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set secrets
      - name: Install SOPS and Age
        run: sudo apt-get install -y sops age

      - name: Configure SOPS
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.SOPS_AGE_KEY }}" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt

      - name: Decrypt secrets
        run: |
          sops --decrypt project/manifests/backend_manifests/secrets.enc.yaml > project/manifests/backend_manifests/secrets.yaml


      # Docker Hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Google Cloud auth
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Get GKE credentials
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      # Set Namespace by branch
      - name: Set Namespace
        run: |
          if [[ "$BRANCH" == "main" ]]; then
            echo "NAMESPACE=project-namespace" >> $GITHUB_ENV
          else
            echo "NAMESPACE=${BRANCH}" >> $GITHUB_ENV
          fi

      - name: Create Namespace (if not exists)
        run: |
          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE

       # Build and push todo-app image
      - name: Build and Push Frontend Image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/todo-app:$BRANCH-$GITHUB_SHA -t $DOCKER_HUB_USERNAME/todo-app:latest -f ./project/Dockerfile ./project
          docker push $DOCKER_HUB_USERNAME/todo-app:latest

      # Build and push todo-backend image
      - name: Build and Push Backend Image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/todo-backend:$BRANCH-$GITHUB_SHA -t $DOCKER_HUB_USERNAME/todo-backend:latest -f ./project/todo_backend/Dockerfile ./project/todo_backend
          docker push $DOCKER_HUB_USERNAME/todo-backend:latest

      # Kustomize
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      # Update Kustomize images and deploy 
      - name: Deploy to GKE
        run: |
          cd project/manifests
          NAMESPACE=${GITHUB_REF#refs/heads/}
          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE
          kustomize edit set namespace $NAMESPACE
          kustomize build . | kubectl apply -f -
          kubectl rollout restart deployment todo-app-dep -n $NAMESPACE
          kubectl rollout restart deployment todo-backend-dep -n $NAMESPACE
          kubectl get services -o wide -n $NAMESPACE
